name: h2o_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #cache
  uuid: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  get_it: ^7.6.4
  sqflite: ^2.3.0
  alarm: ^2.1.0
  #network
  connectivity_plus: ^4.0.2
  #state
  flutter_riverpod: ^2.4.0
  #google
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  #test
  path_provider: ^2.1.1
  #language
  easy_localization: ^3.0.3
  #material
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  numberpicker: ^2.1.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.63.0
  intl: ^0.18.1
  flutter_datetime_picker: ^1.5.1
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf


